declare const classNames: {
  readonly selectWrapper: "selectWrapper";
  readonly container: "container";
  readonly arrow: "arrow";
  readonly placeholder: "placeholder";
  readonly select: "select";
  readonly option: "option";
  readonly "option-black": "option-black";
  readonly "option-white": "option-white";
  readonly "option-gray": "option-gray";
  readonly "option-pink": "option-pink";
  readonly "option-fuchsia": "option-fuchsia";
  readonly "option-yellow": "option-yellow";
  readonly "option-green": "option-green";
  readonly "option-blue": "option-blue";
  readonly "option-purple": "option-purple";
  readonly "option-wide": "option-wide";
  readonly "option-narrow": "option-narrow";
};
export default classNames;
